#!/bin/bash

PATHNAME=$@

if [[ ! -n $PATHNAME ]]; then
  echo "fatal: file not specified"
  exit 1
elif [[ ! -e $PATHNAME ]]; then
  echo "fatal: file does not exist"
  exit 1
fi

echo "Searching for path: \"${PATHNAME}\" in remote branches."

git fetch --prune >/dev/null 2>/dev/null
git checkout master >/dev/null 2>/dev/null
git pull --rebase >/dev/null 2>/dev/null

# search for file
BRANCHES=$(git for-each-ref --format="%(refname:short)" | grep -v master | while read branch; do
  git cherry master $branch | while read x head; do 
    if [ "$(git log -n 1 --format=%H $head -- $PATHNAME)" = "$head" ]; then echo $branch; fi;
  done;
done | sort -u | xargs echo -n)

# print results
if [ -n "$BRANCHES" ]; then
  echo "Path \"${PATHNAME}\" was modified in the following branches:"
  for branch in $BRANCHES; do
    echo " - $(echo $branch | sed 's/origin\///')"
  done
  RETVAL=0
else
  echo "Path \"${PATHNAME}\" was not modified in any of the remote branches."
  RETVAL=1
fi

exit $RETVAL
